networks:
  publish:
    external: true
    name: ${PUBLISH_NETWORK}
  warface_social:

volumes:
  mysql_data:
    name: testers_warface_social_network_db
    external: true

services:
  app:
    container_name: testers_warface_social_network
    image: social_network_23.03.01.1600 # build truoc
    networks:
      - publish
      - warface_social
    depends_on:
      - db
    restart: unless-stopped


  db:
    platform: linux/amd64
    build:
      context: ./database
    networks:
      - warface_social
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    restart: unless-stopped
